// setup-oauth.js
// Script hỗ trợ tạo file .env cho OAuth2

const fs = require('fs');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function setupOAuth() {
    console.log('=== THIẾT LẬP OAUTH2 CHO TECHSTORE ===\n');
    console.log('Bạn cần có Google OAuth2 Client ID và Client Secret từ Google Cloud Console.');
    console.log('Nếu chưa có, hãy làm theo các bước sau:\n');
    console.log('1. Truy cập: https://console.cloud.google.com/');
    console.log('2. Tạo project mới hoặc chọn project hiện có');
    console.log('3. Vào APIs & Services > OAuth consent screen (cấu hình trước)');
    console.log('4. Vào APIs & Services > Credentials');
    console.log('5. Click "Create Credentials" > "OAuth client ID"');
    console.log('6. Chọn "Web application"');
    console.log('7. Điền:');
    console.log('   - Authorized JavaScript origins: http://localhost:5000');
    console.log('   - Authorized redirect URIs: http://localhost:5000/api/auth/google/callback');
    console.log('8. Copy Client ID và Client Secret\n');

    const hasCredentials = await question('Bạn đã có Client ID và Client Secret chưa? (y/n): ');
    
    if (hasCredentials.toLowerCase() !== 'y' && hasCredentials.toLowerCase() !== 'yes') {
        console.log('\nVui lòng làm theo hướng dẫn trên để lấy credentials, sau đó chạy lại script này.');
        rl.close();
        return;
    }

    console.log('\nNhập thông tin OAuth2:\n');
    
    const clientId = await question('Google Client ID: ');
    const clientSecret = await question('Google Client Secret: ');
    const callbackUrl = await question('Callback URL (Enter để dùng mặc định): ') || 'http://localhost:5000/api/auth/google/callback';

    if (!clientId || !clientSecret) {
        console.log('\n❌ Client ID và Client Secret không được để trống!');
        rl.close();
        return;
    }

    // Tạo nội dung file .env
    const envContent = `# Google OAuth2 Configuration
# Generated by setup-oauth.js

GOOGLE_CLIENT_ID=${clientId}
GOOGLE_CLIENT_SECRET=${clientSecret}
GOOGLE_CALLBACK_URL=${callbackUrl}
`;

    // Kiểm tra file .env đã tồn tại chưa
    if (fs.existsSync('.env')) {
        const overwrite = await question('\nFile .env đã tồn tại. Ghi đè? (y/n): ');
        if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
            console.log('\nĐã hủy. File .env không được thay đổi.');
            rl.close();
            return;
        }
    }

    // Ghi file .env
    try {
        fs.writeFileSync('.env', envContent);
        console.log('\n✅ Đã tạo file .env thành công!');
        console.log('\n📝 Nội dung file .env:');
        console.log('─'.repeat(50));
        console.log(envContent);
        console.log('─'.repeat(50));
        console.log('\n⚠️  LƯU Ý:');
        console.log('   - File .env chứa thông tin nhạy cảm, KHÔNG commit vào Git');
        console.log('   - Hãy restart server để áp dụng cấu hình mới');
        console.log('   - Chạy: node server.js');
    } catch (error) {
        console.error('\n❌ Lỗi khi tạo file .env:', error.message);
    }

    rl.close();
}

setupOAuth();


