# Script PowerShell để tạo file .env

Write-Host "=== TẠO FILE .ENV CHO OAUTH2 ===" -ForegroundColor Cyan
Write-Host ""

# Kiểm tra file .env đã tồn tại chưa
if (Test-Path .env) {
    Write-Host "⚠️  File .env đã tồn tại!" -ForegroundColor Yellow
    $overwrite = Read-Host "Bạn có muốn ghi đè không? (y/n)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Đã hủy." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "Nhập thông tin OAuth2 từ Google Cloud Console:" -ForegroundColor Green
Write-Host ""

# Nhập Client ID
$clientId = Read-Host "Google Client ID (dạng: xxxxx.apps.googleusercontent.com)"
if ([string]::IsNullOrWhiteSpace($clientId)) {
    Write-Host "❌ Client ID không được để trống!" -ForegroundColor Red
    exit
}

# Nhập Client Secret
$clientSecret = Read-Host "Google Client Secret (dạng: GOCSPX-xxxxx)"
if ([string]::IsNullOrWhiteSpace($clientSecret)) {
    Write-Host "❌ Client Secret không được để trống!" -ForegroundColor Red
    exit
}

# Callback URL
$callbackUrl = Read-Host "Callback URL (Enter để dùng mặc định)"
if ([string]::IsNullOrWhiteSpace($callbackUrl)) {
    $callbackUrl = "http://localhost:5000/api/auth/google/callback"
}

# Tạo nội dung file .env
$envContent = @"
# Google OAuth2 Configuration
# Generated by tao-file-env.ps1

GOOGLE_CLIENT_ID=$clientId
GOOGLE_CLIENT_SECRET=$clientSecret
GOOGLE_CALLBACK_URL=$callbackUrl
"@

# Ghi file
try {
    $envContent | Out-File -FilePath .env -Encoding utf8 -NoNewline
    Write-Host ""
    Write-Host "✅ Đã tạo file .env thành công!" -ForegroundColor Green
    Write-Host ""
    Write-Host "📝 Nội dung file .env:" -ForegroundColor Cyan
    Write-Host "─" * 50
    Write-Host $envContent
    Write-Host "─" * 50
    Write-Host ""
    Write-Host "⚠️  LƯU Ý:" -ForegroundColor Yellow
    Write-Host "   - File .env chứa thông tin nhạy cảm, KHÔNG commit vào Git"
    Write-Host "   - Hãy restart server để áp dụng cấu hình mới"
    Write-Host "   - Chạy: node server.js"
    Write-Host ""
} catch {
    Write-Host "❌ Lỗi khi tạo file .env: $_" -ForegroundColor Red
}


